version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  dev-db:
    image: postgres:14-alpine
    container_name: dev-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "khukhukhu"
      POSTGRES_PASSWORD: "khukhukhukhukhukhu"
      POSTGRES_DB: "khu"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  express:
    build:
      context: .
      target: dev
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - "5050:5050"
      - "5051:5051"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      API_PORT: 5050
      WS_PORT: 5051
      DB_HOST: dev-db
      KAFKA_URL: kafka:29092